#let acronyms = (
  SSD: "Single Shot MultiBox Detector",
  AP: "Average Precision",
  mAP: "mean Average Precision",
  IoU: "Intersection over Union",
  RGB: "Red, Green, Blue",
  CNN: "Convolutional Neural Network",
  GPU: "Graphics Processing Unit",
  CUDA: "Compute Unified Device Architecture",
  TPU: "Tensor Processing Unit",
  TP: "True Positive",
  FP: "False Positive",
  FN: "False Negative",
  TN: "True Negative",
  MPS: "Metal Performance Shaders",
  FP32: "32-bit floating point",
  FP16: "16-bit floating point",
  INT8: "8-bit integer",
  NMS: "Non-Maximum Suppression",
  VGG: "Visual Geometry Group",
  ResNet: "Residual Network",
  ReLU: "Rectified Linear Unit",
  R-CNN: "Region-based Convolutional Neural Network",
  RPN: "Region Proposal Network",
  ROI: "Region of Interest",
  FPS: "Frames per Second",
  YOLO: "You Only Look Once",
  COCO: "Common Objects in Context",
  VOC: "Visual Object Classes",
  IR: "Infrared",
  AI: "Artificial Intelligence",
  ML: "Machine Learning",
  DL: "Deep Learning",
  RNN: "Recurrent Neural Network",
  GAN: "Generative Adversarial Network",
  SGD: "Stochastic Gradient Descent",
  API: "Application Programming Interface",
  REST: "Representational State Transfer",
  HTTP: "Hypertext Transfer Protocol",
  HTTPS: "Hypertext Transfer Protocol Secure",
  NN: "Neural Network",
  FC: "Fully Connected",
  CPU: "Central Processing Unit",
  RAM: "Random Access Memory",
  TCP: "Transmission Control Protocol",
  OSI: "Open Systems Interconnection",
  HNM: "Hard-Negative Mining",
  ViT: "Vision Transformer",
  HOG: "Histogram of Oriented Gradients",
  AdaBoost: "Adaptive Boosting",
  SVM: "Support Vector Machine",
  VGP: "Vanishing Gradient Problem"
)